FROM node:18-alpine AS build
WORKDIR /app
COPY app/package.json .
RUN npm install
COPY app/ .
RUN  npm run  build


#step 2

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
 
