# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# MySQL Database (Local)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/devopsdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=backend_user
spring.datasource.password=backend_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / JDBC
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.mode=never

# ===============================
# Actuator
# ===============================
management.health.db.enabled=true

